### ISSUE TITLE
Index out of bounds error when adding new songs to partitions

### ISSUE THREAD

**Issue by dearsaturn** [Dimencia/LuteBot3#21]
Whenever I add a new song, I get an index out of bounds error. Here's the exception trace:

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at LuteBot.PartitionsForm.savePartitionsButton_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4515.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
LuteBot
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Lutebot/LuteBot.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4515.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4488.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4395.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4341.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4515.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4161.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 12.0.0.0
    Win32 Version: 12.0.2.23222
    CodeBase: file:///C:/Lutebot/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4161.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4455.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4455.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
Sanford.Multimedia.Midi
    Assembly Version: 6.6.1.0
    Win32 Version: 6.6.1.0
    CodeBase: file:///C:/Lutebot/Sanford.Multimedia.Midi.DLL
----------------------------------------
SimpleML
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Lutebot/SimpleML.DLL
----------------------------------------
netstandard
    Assembly Version: 2.0.0.0
    Win32 Version: 4.8.4161.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
SMDiagnostics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4455.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/SMDiagnostics/v4.0_4.0.0.0__b77a5c561934e089/SMDiagnostics.dll
----------------------------------------
System.ServiceModel.Internals
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4455.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Internals/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Internals.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by Dimencia** [comment]
Can you confirm this happens on 3.4.0 that I just released?  If so, the crash dump it gives may give me more information, if you could paste it here

**Comment by GnightTheBard** [comment]
The same happens to me, i saw that lutebot's version is 1.0.0.0. so i deleted all the oder versions I downloaded before and I used the 3.4.0. Now It says the same just with lutebot version 4.0.0.0. It worked perfectly before the eastern invasion update, if that helps. Also, the songs I saved before can perfectly run with lutemod.

**Comment by dearsaturn** [comment]
@Dimencia here's a google drive link to the memory dump file: https://drive.google.com/file/d/11hWXcZf3hp_CKQY2rHs1jISEEcAVkGNQ/view?usp=sharing

**Comment by dearsaturn** [comment]
Just an update on this, I completely cleared the sav folder and am still getting this issue. Now I can't store any partitions anymore.

**Comment by Dimencia** [comment]
If you clear the sav folder, you will need to create a PartitionIndex - either by trying to open the LuteMod menu in-game (by kicking with a lute in hand), which should give a message that it generated it the first time, or by downloading it from the repo under the LuteMod Folder and putting it in the sav folder, or by running Options -> Install LuteMod (Not recommended if your lutemod is already working in the game)

I don't know what to do with a dmp file, when the exception occurs it should prompt you that it logged it, with an option to open the folder to those logs; send me those

Ty for reminding me of this by updating the issue, I had forgotten and have been very busy lately.  I will try to investigate more on my own soon, but if you don't hear back soonish, feel free to remind me repeatedly


Otherwise, if you have a PartitionIndex[0] file in there, you might also try clearing LuteBot settings or checking for invalid values under %appdata%/LuteBot/Config

**Comment by Dimencia** [comment]
@sguionni What does your Instruments.json file look like at %appdata%/lutebot/config?  Have you deleted anything from that file?

It is actually supposed to be < 2 rather than < 4, so good catch, but the fact that you don't have those instruments is a red flag

**Comment by Dimencia** [comment]
Do you perhaps have it set to not show Track Filtering?  I think the version I just pushed should fix it

**Comment by GnightTheBard** [comment]
Hi! I fixed the issue. I think It may not be your but the users fault. I accidentaly switched the format of the Configuration.txt and the Instrments.txt file to Configuration.json etc. I renamed them to the original and now the lutebot works perfectly! Hope this could help!
